// <auto-generated />
using System;
using CinemaApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace CinemaApp.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    partial class CinemaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaApp.Models.Customer", b =>
            {
                b.Property<int>("Customer_ID").ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Customer_ID"));
                b.Property<string>("Email").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("FirstName").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
                b.Property<string>("LastName").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
                b.Property<string>("Phone").HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.HasKey("Customer_ID");
                b.ToTable("Customers");
            });

            modelBuilder.Entity("CinemaApp.Models.Film", b =>
            {
                b.Property<int>("Film_ID").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Film_ID"));
                b.Property<string>("Description").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<int?>("Duration").HasColumnType("int");
                b.Property<string>("Genre").HasMaxLength(30).HasColumnType("nvarchar(30)");
                b.Property<double?>("Rating").HasColumnType("float");
                b.Property<int?>("ReleaseYear").HasColumnType("int");
                b.Property<int>("Studio_ID").HasColumnType("int");
                b.Property<string>("Title").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("Film_ID");
                b.HasIndex("Studio_ID");
                b.ToTable("Films");
            });

            modelBuilder.Entity("CinemaApp.Models.Screening", b =>
            {
                b.Property<int>("Screening_ID").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Screening_ID"));
                b.Property<int>("Film_ID").HasColumnType("int");
                b.Property<string>("Hall").HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<DateTime>("StartTime").HasColumnType("datetime2");
                b.Property<double>("TicketPrice").HasColumnType("float");
                b.Property<int>("TotalSeats").HasDefaultValue(100).HasColumnType("int");
                b.HasKey("Screening_ID");
                b.HasIndex("Film_ID");
                b.ToTable("Screenings");
            });

            modelBuilder.Entity("CinemaApp.Models.Studio", b =>
            {
                b.Property<int>("Studio_ID").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Studio_ID"));
                b.Property<string>("Country").HasMaxLength(30).HasColumnType("nvarchar(30)");
                b.Property<int?>("Founded").HasColumnType("int");
                b.Property<string>("Info").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("Studio_ID");
                b.ToTable("Studios");
            });

            modelBuilder.Entity("CinemaApp.Models.Ticket", b =>
            {
                b.Property<int>("Ticket_ID").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ticket_ID"));
                b.Property<int?>("Booking_No").HasColumnType("int");
                b.Property<int>("Customer_ID").HasColumnType("int");
                b.Property<DateOnly>("PurchaseDate").HasColumnType("date");
                b.Property<int>("Quantity").HasDefaultValue(1).HasColumnType("int");
                b.Property<int>("Screening_ID").HasColumnType("int");
                b.Property<int?>("SeatNumber").HasColumnType("int");
                b.HasKey("Ticket_ID");
                b.HasIndex("Customer_ID");
                b.HasIndex("Screening_ID");
                b.ToTable("Tickets");
            });

            modelBuilder.Entity("CinemaApp.Models.TicketsLog", b =>
            {
                b.Property<int>("Log_ID").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Log_ID"));
                b.Property<string>("Action").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
                b.Property<DateTime>("ModifyDate").HasDefaultValueSql("GETDATE()").HasColumnType("datetime2");
                b.Property<int>("Ticket_ID").HasColumnType("int");
                b.HasKey("Log_ID");
                b.ToTable("TicketsLog");
            });

            modelBuilder.Entity("CinemaApp.Models.Film", b =>
            {
                b.HasOne("CinemaApp.Models.Studio", "Studio")
                    .WithMany("Films")
                    .HasForeignKey("Studio_ID")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Studio");
            });

            modelBuilder.Entity("CinemaApp.Models.Screening", b =>
            {
                b.HasOne("CinemaApp.Models.Film", "Film")
                    .WithMany("Screenings")
                    .HasForeignKey("Film_ID")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Film");
            });

            modelBuilder.Entity("CinemaApp.Models.Ticket", b =>
            {
                b.HasOne("CinemaApp.Models.Customer", "Customer")
                    .WithMany("Tickets")
                    .HasForeignKey("Customer_ID")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("CinemaApp.Models.Screening", "Screening")
                    .WithMany("Tickets")
                    .HasForeignKey("Screening_ID")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Customer");
                b.Navigation("Screening");
            });

            modelBuilder.Entity("CinemaApp.Models.Customer", b => { b.Navigation("Tickets"); });
            modelBuilder.Entity("CinemaApp.Models.Film", b => { b.Navigation("Screenings"); });
            modelBuilder.Entity("CinemaApp.Models.Screening", b => { b.Navigation("Tickets"); });
            modelBuilder.Entity("CinemaApp.Models.Studio", b => { b.Navigation("Films"); });
#pragma warning restore 612, 618
        }
    }
}
